/** Common countries for profile settings (ISO 3166-1 display names). */
export const COUNTRIES = [
  "United States",
  "Canada",
  "United Kingdom",
  "Australia",
  "Germany",
  "France",
  "Netherlands",
  "Spain",
  "Italy",
  "Switzerland",
  "Sweden",
  "Norway",
  "Denmark",
  "Finland",
  "Ireland",
  "Belgium",
  "Austria",
  "Portugal",
  "Poland",
  "Czech Republic",
  "Romania",
  "Hungary",
  "Greece",
  "Turkey",
  "Israel",
  "United Arab Emirates",
  "India",
  "Singapore",
  "Japan",
  "South Korea",
  "China",
  "Hong Kong",
  "Taiwan",
  "Mexico",
  "Brazil",
  "Argentina",
  "Chile",
  "Colombia",
  "South Africa",
  "Nigeria",
  "Kenya",
  "Egypt",
  "New Zealand",
  "Philippines",
  "Indonesia",
  "Malaysia",
  "Thailand",
  "Vietnam",
  "Pakistan",
  "Bangladesh",
  "Other",
] as const;

export type Country = (typeof COUNTRIES)[number];
