export type IconSeedEntry = {
  name: string;
  category: string;
  image_url: string;
  source: "manual";
};

const FLAG_COUNTRIES: [string, string][] = [
  ["United States", "us"],
  ["United Kingdom", "gb"],
  ["France", "fr"],
  ["Germany", "de"],
  ["Spain", "es"],
  ["Italy", "it"],
  ["Japan", "jp"],
  ["China", "cn"],
  ["Russia", "ru"],
  ["Brazil", "br"],
  ["Canada", "ca"],
  ["Australia", "au"],
  ["India", "in"],
  ["Mexico", "mx"],
  ["South Korea", "kr"],
  ["Netherlands", "nl"],
  ["Belgium", "be"],
  ["Sweden", "se"],
  ["Norway", "no"],
  ["Denmark", "dk"],
  ["Finland", "fi"],
  ["Switzerland", "ch"],
  ["Austria", "at"],
  ["Portugal", "pt"],
  ["Greece", "gr"],
  ["Turkey", "tr"],
  ["Poland", "pl"],
  ["Ukraine", "ua"],
  ["Israel", "il"],
  ["Saudi Arabia", "sa"],
  ["United Arab Emirates", "ae"],
  ["South Africa", "za"],
  ["Nigeria", "ng"],
  ["Egypt", "eg"],
  ["Argentina", "ar"],
  ["Chile", "cl"],
  ["Colombia", "co"],
  ["Venezuela", "ve"],
  ["New Zealand", "nz"],
  ["Ireland", "ie"],
  ["Scotland", "gb-sct"],
  ["Wales", "gb-wls"],
  ["North Macedonia", "mk"],
  ["Bosnia and Herzegovina", "ba"],
  ["Serbia", "rs"],
];

const CLEARBIT_COMPANIES: [string, string][] = [
  ["Apple", "apple.com"],
  ["Microsoft", "microsoft.com"],
  ["Google", "google.com"],
  ["Alphabet", "abc.xyz"],
  ["Amazon", "amazon.com"],
  ["Meta", "meta.com"],
  ["Tesla", "tesla.com"],
  ["Nvidia", "nvidia.com"],
  ["Netflix", "netflix.com"],
  ["Spotify", "spotify.com"],
  ["Twitter", "twitter.com"],
  ["X", "x.com"],
  ["OpenAI", "openai.com"],
  ["Anthropic", "anthropic.com"],
  ["Coinbase", "coinbase.com"],
  ["Robinhood", "robinhood.com"],
  ["JPMorgan", "jpmorganchase.com"],
  ["Goldman Sachs", "goldmansachs.com"],
  ["Federal Reserve", "federalreserve.gov"],
];

const CRYPTO_COINS: [string, string][] = [
  ["Bitcoin", "https://coin-images.coingecko.com/coins/images/1/large/bitcoin.png"],
  ["Ethereum", "https://coin-images.coingecko.com/coins/images/279/large/ethereum.png"],
  ["BNB", "https://coin-images.coingecko.com/coins/images/825/large/bnb-icon2_2x.png"],
  ["Solana", "https://coin-images.coingecko.com/coins/images/4128/large/solana.png"],
  ["XRP", "https://coin-images.coingecko.com/coins/images/44/large/xrp-symbol-white-128.png"],
  ["USDC", "https://coin-images.coingecko.com/coins/images/6319/large/usdc.png"],
  ["Cardano", "https://coin-images.coingecko.com/coins/images/975/large/cardano.png"],
  ["Dogecoin", "https://coin-images.coingecko.com/coins/images/5/large/dogecoin.png"],
  ["Avalanche", "https://coin-images.coingecko.com/coins/images/12559/large/Avalanche_Circle_RedWhite_Trans.png"],
  ["Polkadot", "https://coin-images.coingecko.com/coins/images/12171/large/polkadot.png"],
  ["Chainlink", "https://coin-images.coingecko.com/coins/images/877/large/chainlink-new-logo.png"],
  ["Litecoin", "https://coin-images.coingecko.com/coins/images/2/large/litecoin.png"],
  ["Bitcoin Cash", "https://coin-images.coingecko.com/coins/images/780/large/bitcoin-cash-circle.png"],
  ["Stellar", "https://coin-images.coingecko.com/coins/images/100/large/Stellar_symbol_black_RGB.png"],
  ["Monero", "https://coin-images.coingecko.com/coins/images/69/large/monero_logo.png"],
  ["TRON", "https://coin-images.coingecko.com/coins/images/1094/large/tron-logo.png"],
  ["Shiba Inu", "https://coin-images.coingecko.com/coins/images/11939/large/shiba.png"],
  ["Uniswap", "https://coin-images.coingecko.com/coins/images/12504/large/uniswap-logo.png"],
  ["Dai", "https://coin-images.coingecko.com/coins/images/9956/large/Badge_Dai.png"],
  ["Pepe", "https://coin-images.coingecko.com/coins/images/29850/large/pepe-token.jpeg"],
  ["Toncoin", "https://coin-images.coingecko.com/coins/images/17980/large/ton_symbol.png"],
  ["Polygon", "https://coin-images.coingecko.com/coins/images/4713/large/polygon.png"],
  ["Internet Computer", "https://coin-images.coingecko.com/coins/images/14495/large/Internet_Computer_logo.png"],
  ["Aptos", "https://coin-images.coingecko.com/coins/images/26455/large/aptos_round.png"],
  ["Arbitrum", "https://coin-images.coingecko.com/coins/images/16547/large/arb.jpg"],
  ["Optimism", "https://coin-images.coingecko.com/coins/images/25244/large/Optimism.png"],
  ["Near", "https://coin-images.coingecko.com/coins/images/10365/large/near.jpg"],
  ["Cosmos", "https://coin-images.coingecko.com/coins/images/1481/large/cosmos_hub.png"],
  ["Filecoin", "https://coin-images.coingecko.com/coins/images/12817/large/filecoin.png"],
  ["Hedera", "https://coin-images.coingecko.com/coins/images/3688/large/hbar.png"],
  ["VeChain", "https://coin-images.coingecko.com/coins/images/1167/large/VET_Token_Icon.png"],
  ["Algorand", "https://coin-images.coingecko.com/coins/images/4380/large/download.png"],
  ["Maker", "https://coin-images.coingecko.com/coins/images/1364/large/Mark_Maker.png"],
  ["Aave", "https://coin-images.coingecko.com/coins/images/12645/large/aave-token-round.png"],
  ["Render", "https://coin-images.coingecko.com/coins/images/11636/large/rndr.png"],
  ["Injective", "https://coin-images.coingecko.com/coins/images/12882/large/Secondary_Symbol.png"],
  ["Sui", "https://coin-images.coingecko.com/coins/images/26375/large/sui_asset.jpeg"],
  ["Sei", "https://coin-images.coingecko.com/coins/images/28205/large/Sei_Logo_-_Transparent.png"],
  ["Celestia", "https://coin-images.coingecko.com/coins/images/31967/large/tia.jpg"],
  ["Bonk", "https://coin-images.coingecko.com/coins/images/28600/large/bonk.jpg"],
  ["Fetch.ai", "https://coin-images.coingecko.com/coins/images/5681/large/Fetch.jpg"],
  ["Immutable", "https://coin-images.coingecko.com/coins/images/17233/large/immutableX-symbol-BLK-RGB.png"],
  ["Stacks", "https://coin-images.coingecko.com/coins/images/2069/large/Stacks_logo_full.png"],
  ["Theta", "https://coin-images.coingecko.com/coins/images/2538/large/theta-token-logo.png"],
  ["Fantom", "https://coin-images.coingecko.com/coins/images/4001/large/Fantom_round.png"],
  ["EOS", "https://coin-images.coingecko.com/coins/images/738/large/eos-eos-logo.png"],
  ["Tezos", "https://coin-images.coingecko.com/coins/images/976/large/Tezos-logo.png"],
  ["Flow", "https://coin-images.coingecko.com/coins/images/13446/large/flow.png"],
  ["Cronos", "https://coin-images.coingecko.com/coins/images/7310/large/cro_token_logo.png"],
  ["Kaspa", "https://coin-images.coingecko.com/coins/images/25751/large/kaspa-icon-exchanges.png"],
];

const NFL_TEAMS: [string, string][] = [
  ["Arizona Cardinals", "ari"],
  ["Atlanta Falcons", "atl"],
  ["Baltimore Ravens", "bal"],
  ["Buffalo Bills", "buf"],
  ["Carolina Panthers", "car"],
  ["Chicago Bears", "chi"],
  ["Cincinnati Bengals", "cin"],
  ["Cleveland Browns", "cle"],
  ["Dallas Cowboys", "dal"],
  ["Denver Broncos", "den"],
  ["Detroit Lions", "det"],
  ["Green Bay Packers", "gb"],
  ["Houston Texans", "hou"],
  ["Indianapolis Colts", "ind"],
  ["Jacksonville Jaguars", "jax"],
  ["Kansas City Chiefs", "kc"],
  ["Las Vegas Raiders", "lv"],
  ["Los Angeles Chargers", "lac"],
  ["Los Angeles Rams", "lar"],
  ["Miami Dolphins", "mia"],
  ["Minnesota Vikings", "min"],
  ["New England Patriots", "ne"],
  ["New Orleans Saints", "no"],
  ["New York Giants", "nyg"],
  ["New York Jets", "nyj"],
  ["Philadelphia Eagles", "phi"],
  ["Pittsburgh Steelers", "pit"],
  ["San Francisco 49ers", "sf"],
  ["Seattle Seahawks", "sea"],
  ["Tampa Bay Buccaneers", "tb"],
  ["Tennessee Titans", "ten"],
  ["Washington Commanders", "wsh"],
];

const NBA_TEAMS: [string, string][] = [
  ["Atlanta Hawks", "atl"],
  ["Boston Celtics", "bos"],
  ["Brooklyn Nets", "bkn"],
  ["Charlotte Hornets", "cha"],
  ["Chicago Bulls", "chi"],
  ["Cleveland Cavaliers", "cle"],
  ["Dallas Mavericks", "dal"],
  ["Denver Nuggets", "den"],
  ["Detroit Pistons", "det"],
  ["Golden State Warriors", "gs"],
  ["Houston Rockets", "hou"],
  ["Indiana Pacers", "ind"],
  ["Los Angeles Clippers", "lac"],
  ["Los Angeles Lakers", "lal"],
  ["Memphis Grizzlies", "mem"],
  ["Miami Heat", "mia"],
  ["Milwaukee Bucks", "mil"],
  ["Minnesota Timberwolves", "min"],
  ["New Orleans Pelicans", "nop"],
  ["New York Knicks", "nyk"],
  ["Oklahoma City Thunder", "okc"],
  ["Orlando Magic", "orl"],
  ["Philadelphia 76ers", "phi"],
  ["Phoenix Suns", "phx"],
  ["Portland Trail Blazers", "por"],
  ["Sacramento Kings", "sac"],
  ["San Antonio Spurs", "sas"],
  ["Toronto Raptors", "tor"],
  ["Utah Jazz", "uta"],
  ["Washington Wizards", "was"],
];

const MLB_TEAMS: [string, string][] = [
  ["Arizona Diamondbacks", "ari"],
  ["Atlanta Braves", "atl"],
  ["Baltimore Orioles", "bal"],
  ["Boston Red Sox", "bos"],
  ["Chicago Cubs", "chc"],
  ["Chicago White Sox", "chw"],
  ["Cincinnati Reds", "cin"],
  ["Cleveland Guardians", "cle"],
  ["Colorado Rockies", "col"],
  ["Detroit Tigers", "det"],
  ["Houston Astros", "hou"],
  ["Kansas City Royals", "kc"],
  ["Los Angeles Angels", "laa"],
  ["Los Angeles Dodgers", "lad"],
  ["Miami Marlins", "mia"],
  ["Milwaukee Brewers", "mil"],
  ["Minnesota Twins", "min"],
  ["New York Mets", "nym"],
  ["New York Yankees", "nyy"],
  ["Oakland Athletics", "oak"],
  ["Philadelphia Phillies", "phi"],
  ["Pittsburgh Pirates", "pit"],
  ["San Diego Padres", "sd"],
  ["San Francisco Giants", "sf"],
  ["Seattle Mariners", "sea"],
  ["St. Louis Cardinals", "stl"],
  ["Tampa Bay Rays", "tb"],
  ["Texas Rangers", "tex"],
  ["Toronto Blue Jays", "tor"],
  ["Washington Nationals", "wsh"],
];

const NHL_TEAMS: [string, string][] = [
  ["Anaheim Ducks", "ana"],
  ["Boston Bruins", "bos"],
  ["Buffalo Sabres", "buf"],
  ["Calgary Flames", "cgy"],
  ["Carolina Hurricanes", "car"],
  ["Chicago Blackhawks", "chi"],
  ["Colorado Avalanche", "col"],
  ["Columbus Blue Jackets", "cbj"],
  ["Dallas Stars", "dal"],
  ["Detroit Red Wings", "det"],
  ["Edmonton Oilers", "edm"],
  ["Florida Panthers", "fla"],
  ["Los Angeles Kings", "la"],
  ["Minnesota Wild", "min"],
  ["Montreal Canadiens", "mtl"],
  ["Nashville Predators", "nsh"],
  ["New Jersey Devils", "nj"],
  ["New York Islanders", "nyi"],
  ["New York Rangers", "nyr"],
  ["Ottawa Senators", "ott"],
  ["Philadelphia Flyers", "phi"],
  ["Pittsburgh Penguins", "pit"],
  ["San Jose Sharks", "sj"],
  ["Seattle Kraken", "sea"],
  ["St. Louis Blues", "stl"],
  ["Tampa Bay Lightning", "tb"],
  ["Toronto Maple Leafs", "tor"],
  ["Vancouver Canucks", "van"],
  ["Vegas Golden Knights", "vgk"],
  ["Washington Capitals", "wsh"],
  ["Winnipeg Jets", "wpg"],
];

const EPL_TEAMS: [string, string][] = [
  ["Arsenal", "359"],
  ["Aston Villa", "362"],
  ["Bournemouth", "349"],
  ["Brentford", "3370"],
  ["Brighton", "331"],
  ["Chelsea", "363"],
  ["Crystal Palace", "384"],
  ["Everton", "368"],
  ["Fulham", "370"],
  ["Ipswich Town", "374"],
  ["Leicester City", "375"],
  ["Liverpool", "364"],
  ["Manchester City", "382"],
  ["Manchester United", "360"],
  ["Newcastle United", "361"],
  ["Nottingham Forest", "393"],
  ["Southampton", "376"],
  ["Tottenham Hotspur", "367"],
  ["West Ham United", "371"],
  ["Wolverhampton Wanderers", "380"],
];

const POLITICIANS: IconSeedEntry[] = [
  { name: "Gavin Newsom", category: "Elections", image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Governor_of_California_Gavin_Newsom_%28cropped_3x4%29.jpg/250px-Governor_of_California_Gavin_Newsom_%28cropped_3x4%29.jpg", source: "manual" },
  { name: "Alexandria Ocasio-Cortez", category: "Elections", image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Alexandria_Ocasio-Cortez_Official_Portrait.jpg/250px-Alexandria_Ocasio-Cortez_Official_Portrait.jpg", source: "manual" },
  { name: "Marco Rubio", category: "Elections", image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/Official_portrait_of_Secretary_Marco_Rubio_%28cropped%29%282%29.jpg/250px-Official_portrait_of_Secretary_Marco_Rubio_%28cropped%29%282%29.jpg", source: "manual" },
  { name: "JD Vance", category: "Elections", image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/March_2026_Official_Vice_Presidential_Portrait_of_JD_Vance_%28head-and-shoulders_cropped%29.jpg/250px-March_2026_Official_Vice_Presidential_Portrait_of_JD_Vance_%28head-and-shoulders_cropped%29.jpg", source: "manual" },
  { name: "Andy Burnham", category: "Elections", image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Andy_Burnham_on_13_August_2024_%28cropped_2%29.jpg/250px-Andy_Burnham_on_13_August_2024_%28cropped_2%29.jpg", source: "manual" },
  { name: "Ed Miliband", category: "Elections", image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Secretary_of_State_for_Energy_Security_and_Net_Zero_Ed_Miliband_%2855066031341%29_%28cropped%29.jpg/250px-Secretary_of_State_for_Energy_Security_and_Net_Zero_Ed_Miliband_%2855066031341%29_%28cropped%29.jpg", source: "manual" },
  { name: "Gretchen Whitmer", category: "Elections", image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/2025_Gretchen_Whitmer_%28cropped%29.jpg/250px-2025_Gretchen_Whitmer_%28cropped%29.jpg", source: "manual" },
  { name: "Andy Beshear", category: "Elections", image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Andy_Beshear_in_April_2026_%28cropped%29.jpg/250px-Andy_Beshear_in_April_2026_%28cropped%29.jpg", source: "manual" },
  { name: "Donald Trump", category: "Elections", image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Official_Presidential_Portrait_of_President_Donald_J._Trump_%282025%29_%28cropped%29%282%29.jpg/250px-Official_Presidential_Portrait_of_President_Donald_J._Trump_%282025%29_%28cropped%29%282%29.jpg", source: "manual" },
  { name: "Joe Biden", category: "Elections", image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/Joe_Biden_presidential_portrait.jpg/250px-Joe_Biden_presidential_portrait.jpg", source: "manual" },
  { name: "Kamala Harris", category: "Elections", image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Kamala_Harris_Vice_Presidential_Portrait.jpg/250px-Kamala_Harris_Vice_Presidential_Portrait.jpg", source: "manual" },
  { name: "Ron DeSantis", category: "Elections", image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Ron_DeSantis_official_photo.jpg/250px-Ron_DeSantis_official_photo.jpg", source: "manual" },
  { name: "Nikki Haley", category: "Elections", image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/75/Nikki_Haley_official_photo.jpg/250px-Nikki_Haley_official_photo.jpg", source: "manual" },
  { name: "Vivek Ramaswamy", category: "Elections", image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Vivek_Ramaswamy_2026_%28cropped%29.jpg/250px-Vivek_Ramaswamy_2026_%28cropped%29.jpg", source: "manual" },
  { name: "Chris Christie", category: "Elections", image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Chris_Christie_in_Baltimore2022%28crop%29.jpg/250px-Chris_Christie_in_Baltimore2022%28crop%29.jpg", source: "manual" },
  { name: "Tim Scott", category: "Elections", image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Tim_Scott_official_portrait_%28cropped%29.jpg/250px-Tim_Scott_official_portrait_%28cropped%29.jpg", source: "manual" },
  { name: "Mike Pence", category: "Elections", image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Mike_Pence_official_Vice_Presidential_portrait.jpg/250px-Mike_Pence_official_Vice_Presidential_portrait.jpg", source: "manual" },
  { name: "Mike Pompeo", category: "Elections", image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Mike_Pompeo_official_photo_%28cropped%29%282%29.jpg/250px-Mike_Pompeo_official_photo_%28cropped%29%282%29.jpg", source: "manual" },
  { name: "Greg Abbott", category: "Elections", image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/Greg_Abbott_at_NASA_2024_%28cropped%29.jpg/250px-Greg_Abbott_at_NASA_2024_%28cropped%29.jpg", source: "manual" },
  { name: "Kathy Hochul", category: "Elections", image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Governor_Kathy_Hochul_Press_Conference_%28cropped%29.jpg/250px-Governor_Kathy_Hochul_Press_Conference_%28cropped%29.jpg", source: "manual" },
  { name: "Wes Moore", category: "Elections", image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Governor_Wes_Moore_%28cropped%29.jpg/250px-Governor_Wes_Moore_%28cropped%29.jpg", source: "manual" },
  { name: "Josh Shapiro", category: "Elections", image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Josh_Shapiro_2023_%28cropped%29.jpg/250px-Josh_Shapiro_2023_%28cropped%29.jpg", source: "manual" },
  { name: "Jared Polis", category: "Elections", image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Jared_Polis_official_photo_%28cropped%29.jpg/250px-Jared_Polis_official_photo_%28cropped%29.jpg", source: "manual" },
  { name: "Tony Evers", category: "Elections", image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Tony_Evers_%28cropped%29.jpg/250px-Tony_Evers_%28cropped%29.jpg", source: "manual" },
  { name: "JB Pritzker", category: "Elections", image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/JB_Pritzker_2019_%28cropped%29.jpg/250px-JB_Pritzker_2019_%28cropped%29.jpg", source: "manual" },
  { name: "Pritzker", category: "Elections", image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/JB_Pritzker_2019_%28cropped%29.jpg/250px-JB_Pritzker_2019_%28cropped%29.jpg", source: "manual" },
  { name: "Whitmer", category: "Elections", image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/2025_Gretchen_Whitmer_%28cropped%29.jpg/250px-2025_Gretchen_Whitmer_%28cropped%29.jpg", source: "manual" },
];

const PARTIES: IconSeedEntry[] = [
  { name: "Democratic Party", category: "Elections", image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/Democratic_Donkey.svg/250px-Democratic_Donkey.svg.png", source: "manual" },
  { name: "Republican Party", category: "Elections", image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Republicanlogo.svg/250px-Republicanlogo.svg.png", source: "manual" },
  { name: "Labour Party", category: "Politics", image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Labour_Party_%28UK%29_logo.svg/250px-Labour_Party_%28UK%29_logo.svg.png", source: "manual" },
  { name: "Conservative Party", category: "Politics", image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Conservative_Party_logo_%28UK%29.svg/250px-Conservative_Party_logo_%28UK%29.svg.png", source: "manual" },
  { name: "Reform UK", category: "Politics", image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/58/Reform_UK_logo.svg/250px-Reform_UK_logo.svg.png", source: "manual" },
  { name: "Liberal Democrats", category: "Politics", image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Liberal_Democrats_logo_%282019%29.svg/250px-Liberal_Democrats_logo_%282019%29.svg.png", source: "manual" },
  { name: "Green Party", category: "Politics", image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Green_Party_of_the_United_States_logo.svg/250px-Green_Party_of_the_United_States_logo.svg.png", source: "manual" },
  { name: "Independent", category: "Elections", image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Independent_candidate_icon.svg/250px-Independent_candidate_icon.svg.png", source: "manual" },
  { name: "Democratic Sweep", category: "Elections", image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/Democratic_Donkey.svg/250px-Democratic_Donkey.svg.png", source: "manual" },
  { name: "Republican Sweep", category: "Elections", image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Republicanlogo.svg/250px-Republicanlogo.svg.png", source: "manual" },
];

function flagEntries(): IconSeedEntry[] {
  return FLAG_COUNTRIES.map(([name, code]) => ({
    name,
    category: "Climate",
    image_url: `https://flagcdn.com/w80/${code.toLowerCase()}.png`,
    source: "manual" as const,
  }));
}

function clearbitEntries(): IconSeedEntry[] {
  return CLEARBIT_COMPANIES.map(([name, domain]) => ({
    name,
    category: "Finance",
    image_url: `https://logo.clearbit.com/${domain}`,
    source: "manual" as const,
  }));
}

function cryptoEntries(): IconSeedEntry[] {
  return CRYPTO_COINS.map(([name, url]) => ({
    name,
    category: "Crypto",
    image_url: url,
    source: "manual" as const,
  }));
}

function nflEntries(): IconSeedEntry[] {
  return NFL_TEAMS.map(([name, abbr]) => ({
    name,
    category: "Sports",
    image_url: `https://a.espncdn.com/i/teamlogos/nfl/500/${abbr}.png`,
    source: "manual" as const,
  }));
}

function nbaEntries(): IconSeedEntry[] {
  return NBA_TEAMS.map(([name, abbr]) => ({
    name,
    category: "Sports",
    image_url: `https://a.espncdn.com/i/teamlogos/nba/500/${abbr}.png`,
    source: "manual" as const,
  }));
}

function mlbEntries(): IconSeedEntry[] {
  return MLB_TEAMS.map(([name, abbr]) => ({
    name,
    category: "Sports",
    image_url: `https://a.espncdn.com/i/teamlogos/mlb/500/${abbr}.png`,
    source: "manual" as const,
  }));
}

function nhlEntries(): IconSeedEntry[] {
  return NHL_TEAMS.map(([name, abbr]) => ({
    name,
    category: "Sports",
    image_url: `https://a.espncdn.com/i/teamlogos/nhl/500/${abbr}.png`,
    source: "manual" as const,
  }));
}

function eplEntries(): IconSeedEntry[] {
  return EPL_TEAMS.map(([name, id]) => ({
    name,
    category: "Sports",
    image_url: `https://a.espncdn.com/i/teamlogos/soccer/500/${id}.png`,
    source: "manual" as const,
  }));
}

/** Pre-verified icon mappings seeded at deploy time. */
export const ICON_SEED_DATA: IconSeedEntry[] = [
  ...POLITICIANS,
  ...PARTIES,
  ...flagEntries(),
  ...clearbitEntries(),
  ...cryptoEntries(),
  ...nflEntries(),
  ...nbaEntries(),
  ...mlbEntries(),
  ...nhlEntries(),
  ...eplEntries(),
];
